services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: frontend.Dockerfile

    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
    restart: always
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: backend.Dockerfile
    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - ./service:/app/service
    restart: always
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

networks:
  sebassnoob-website-network:
    name: ${APP_NAME}-network
    driver: bridge
