version: "3"

services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: frontend.Dockerfile

    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: always
    ports:
      - 3000:3000
  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: backend.Dockerfile
    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    volumes:
      - ./server:/app/server
    restart: always
    ports:
      - 5000:5000

networks:
  sebassnoob-website-network:
    name: ${APP_NAME}-network
    driver: bridge
