services:
  frontend:
    container_name: ${FRONTEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: frontend.Dockerfile

    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    restart: on-failure
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  backend:
    container_name: ${BACKEND_CONTAINER_NAME}
    build:
      context: ./
      dockerfile: backend.Dockerfile
    networks:
      - ${APP_NAME}-network
    env_file:
      - .env
    
    restart: on-failure
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}

networks:
  sebassnoob-website-network:
    name: ${APP_NAME}-network
    driver: bridge
